/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-30 05:25:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:contains", org.apache.taglibs.standard.functions.Functions.class, "contains", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/D:/Works/SF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/insurance/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1764828110010L));
    _jspx_dependants.put("/WEB-INF/views/includes/footer.jsp", Long.valueOf(1766706892000L));
    _jspx_dependants.put("jar:file:/D:/Works/SF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/insurance/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("jar:file:/D:/Works/SF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/insurance/WEB-INF/lib/spring-security-taglibs-6.5.5.jar!/META-INF/security.tld", Long.valueOf(1758086692000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-6.5.5.jar", Long.valueOf(1766461412987L));
    _jspx_dependants.put("/WEB-INF/views/includes/header.jsp", Long.valueOf(1766732112515L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.release();
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <title>Admin Panel</title>\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  \n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- Top Navbar -->\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-custom px-4\">\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">AdminPanel</a>\n");
      out.write("    <div class=\"collapse navbar-collapse\">\n");
      out.write("      <ul class=\"navbar-nav me-auto\">\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Dashboard</a></li>\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Users</a></li>\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Settings</a></li>\n");
      out.write("      </ul>\n");
      out.write("      <span class=\"navbar-text\">\n");
      out.write("        Logged in as <strong>admin</strong> | <a href=\"/account/logout\" class=\"text-white text-decoration-underline\">Logout</a>\n");
      out.write("      </span>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <!-- Sidebar + Content -->\n");
      out.write("  <div class=\"main-wrapper\">\n");
      out.write("    <!-- Sidebar -->\n");
      out.write("    <div class=\"sidebar pt-3\">\n");
      out.write("      <div class=\"list-group list-group-flush\">\n");
      out.write("        <a href=\"#\" class=\"list-group-item active\">Dashboard</a>\n");
      out.write("        <a href=\"#\" class=\"list-group-item\">Analytics</a>\n");
      out.write("        <a href=\"#\" class=\"list-group-item\">User List</a>\n");
      out.write("        <a href=\"#\" class=\"list-group-item\">Roles</a>\n");
      out.write("        <a href=\"#\" class=\"list-group-item\">System Logs</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Main Content -->\n");
      out.write("    <div class=\"content\">    ");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"row justify-content-center\">\n");
      out.write("  <div class=\"col-lg-12\">\n");
      out.write("    <div class=\"card shadow mb-4\">\n");
      out.write("      <div class=\"card-header py-3\">\n");
      out.write("        <h6 class=\"m-0 fw-bold text-primary\">Board Read</h6>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card-body\">\n");
      out.write("        \n");
      out.write("        <div class=\"mb-3 input-group input-group-lg\">\n");
      out.write("          <span class=\"input-group-text\">Bno</span>\n");
      out.write("          <input type=\"text\" class=\"form-control\" value=\"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\" readonly>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"mb-3 input-group input-group-lg\">\n");
      out.write("          <span class=\"input-group-text\">Title</span>\n");
      out.write("          <input type=\"text\" name=\"title\" class=\"form-control\" value=\"");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\" readonly>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"mb-3 input-group input-group-lg\">\n");
      out.write("          <span class=\"input-group-text\">Content</span>\n");
      out.write("          <textarea class=\"form-control\" name=\"content\" rows=\"3\" readonly>");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("</textarea>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"mb-3 input-group input-group-lg\">\n");
      out.write("          <span class=\"input-group-text\">Writer</span>\n");
      out.write("          <input type=\"text\" name=\"writer\" class=\"form-control\" value=\"");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("\" readonly>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"mb-3 input-group input-group-lg\">\n");
      out.write("          <span class=\"input-group-text\">RegDate</span>\n");
      out.write("          <input type=\"text\" name=\"regDate\" class=\"form-control\" value=\"");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("\" readonly>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"float-end\">\n");
      out.write("           ");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("           <a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readUrl}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\n");
      out.write("             <button type=\"button\" class=\"btn btn-info btnList\" >LIST</button>\n");
      out.write("           </a>\n");
      out.write("           \n");
      out.write("           ");
      if (_jspx_meth_sec_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("           ");
      if (_jspx_meth_sec_005fauthentication_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("           \n");
      out.write("          ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"col-lg-12\">\n");
      out.write("    <div class=\"card shadow mb-4\">\n");
      out.write("    <div class='m-4'>\n");
      out.write("        <!--댓글 작성 폼 -->\n");
      out.write("      <form id=\"replyForm\" class=\"mt-4\">\n");
      out.write("        <!-- 게시글 번호 hidden 처리 -->\n");
      out.write("        <input type=\"hidden\" name=\"bno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("      \n");
      out.write("        <div class=\"mb-3 input-group input-group-lg\">\n");
      out.write("          <span class=\"input-group-text\">Replyer</span>\n");
      out.write("          <input type=\"text\" name=\"replyer\" class=\"form-control\" required />\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("        <div class=\"mb-3 input-group\">\n");
      out.write("          <span class=\"input-group-text\">Reply Text</span>\n");
      out.write("          <textarea name=\"replyText\" class=\"form-control\" rows=\"3\" required></textarea>\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("        <div class=\"text-end\">\n");
      out.write("          <button type=\"submit\" class=\"btn btn-primary addReplyBtn\">Submit Reply</button>\n");
      out.write("        </div>\n");
      out.write("			</form>\n");
      out.write("			<!-- 댓글 작성 폼 끝 -->\n");
      out.write("		</div>	\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"col-lg-12\">\n");
      out.write("  <div class=\"card shadow mb-4\">\n");
      out.write("      <div class='m-4'>\n");
      out.write("        <!--댓글 목록 -->\n");
      out.write("      <ul class=\"list-group replyList\">\n");
      out.write("        <li class=\"list-group-item\">\n");
      out.write("          <div class=\"d-flex justify-content-between\">\n");
      out.write("            <div>\n");
      out.write("              <strong>번호</strong> - 댓글 내용\n");
      out.write("            </div>\n");
      out.write("            <div class=\"text-muted small\">\n");
      out.write("              작성일\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"mt-1 text-secondary small\">\n");
      out.write("            작성자\n");
      out.write("          </div>\n");
      out.write("        </li>\n");
      out.write(" 	  </ul> <!-- 댓글 목록 -->\n");
      out.write("\n");
      out.write("      <div aria-label=\"댓글 페이지 네비게이션\" class=\"mt-4\">\n");
      out.write("        <ul class=\"pagination justify-content-center\">\n");
      out.write("          <li class=\"page-item disabled\">\n");
      out.write("            <a class=\"page-link\" href=\"#\" tabindex=\"-1\">이전</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"page-item active\">\n");
      out.write("            <a class=\"page-link\" href=\"#\">1</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"page-item\">\n");
      out.write("            <a class=\"page-link\" href=\"#\">2</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"page-item\">\n");
      out.write("            <a class=\"page-link\" href=\"#\">3</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"page-item\">\n");
      out.write("            <a class=\"page-link\" href=\"#\">다음</a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("      <!-- 페이징 끝 -->      \n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"replyModal\" tabindex=\"-1\" aria-labelledby=\"replyModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"replyModalLabel\">댓글 수정 / 삭제</h5>\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"modal-body\">      \n");
      out.write("        <form id=\"replyModForm\">\n");
      out.write("          <input type=\"hidden\" name=\"rno\" value=\"33\">\n");
      out.write("          <div class=\"mb-3\">\n");
      out.write("            <label for=\"replyText\" class=\"form-label\">댓글 내용</label>\n");
      out.write("            <input type=\"text\" name=\"replyText\" id=\"replyText\" class=\"form-control\" value=\"Reply Text\"/>\n");
      out.write("          </div>\n");
      out.write("        </form>        \n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary btnReplyMod\">수정</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger btnReplyDel\">삭제</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">닫기</button>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	\n");
      out.write("//HTML에서 id가 \"replyForm\"인 폼(form) 요소를 찾아 변수에 저장합니다.\n");
      out.write("const replyForm = document.querySelector(\"#replyForm\");\n");
      out.write("	\n");
      out.write("// 클래스가 \"addReplyBtn\"인 버튼을 찾아 클릭 이벤트 리스너를 등록합니다.\n");
      out.write("document.querySelector(\".addReplyBtn\").addEventListener(\"click\", e=>{\n");
      out.write("    \n");
      out.write("    // 폼 제출 시 페이지가 새로고침되는 브라우저의 기본 동작을 막습니다.\n");
      out.write("    e.preventDefault();\n");
      out.write("    \n");
      out.write("    // 클릭 이벤트가 상위 요소로 퍼져나가는 것(버블링)을 방지합니다.\n");
      out.write("    e.stopPropagation();		\n");
      out.write("    \n");
      out.write("    // 폼(replyForm) 안에 입력된 모든 데이터를 FormData 객체로 생성합니다.\n");
      out.write("    const formData = new FormData(replyForm);\n");
      out.write("    \n");
      out.write("    // FormData의 데이터를 서버로 보내기 좋게 일반 객체(Key: Value 형태)로 변환합니다.\n");
      out.write("    // ※ 주의: 소문자 object가 아니라 대문자 Object로 써야 에러가 나지 않습니다.\n");
      out.write("    const data = Object.fromEntries(formData.entries());\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    const jsonData = JSON.stringify(data);\n");
      out.write("    \n");
      out.write("    console.log(\"---------jsonData------------\")\n");
      out.write("    console.log(data);\n");
      out.write("    console.log(jsonData)\n");
      out.write("    \n");
      out.write("    // axios 라이브러리를 사용해 \"/replies\" 주소로 POST 방식의 데이터 전송을 요청합니다.\n");
      out.write("    axios.post(\"/replies\", jsonData, {\n");
      out.write("          headers: {\n");
      out.write("              // 보내는 데이터의 형식이 JSON임을 서버에 알려줍니다.\n");
      out.write("              'Content-Type': 'application/json' \n");
      out.write("          }\n");
      out.write("    })\n");
      out.write("    // 서버 전송에 성공했을 때 실행되는 구간입니다.\n");
      out.write("    .then(res => {\n");
      out.write("          console.log(\"------성공 응답-------------\");\n");
      out.write("          console.log(res.data); // 서버에서 보내준 결과 데이터를 콘솔에 출력합니다.\n");
      out.write("          \n");
      out.write("         // 전송이 성공했으므로 폼에 입력되어 있던 내용을 모두 비웁니다.\n");
      out.write("          replyForm.reset();\n");
      out.write("          getReplies(1, true);\n");
      out.write("    })\n");
      out.write("    // 서버 전송 중 에러가 발생했을 때 실행되는 구간입니다.\n");
      out.write("    .catch(err => {\n");
      out.write("         // 에러 메시지와 함께 서버의 응답 내용을 콘솔에 출력합니다.\n");
      out.write("        console.error(\"여전히 에러가 난다면 서버 코드를 확인하세요!\", err.response);\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("}, false); // 이벤트 캡처링 단계를 사용하지 않겠다는 의미의 기본값입니다.\n");
      out.write("\n");
      out.write("let currentPage = 1;\n");
      out.write("let currentSize = 10;\n");
      out.write("\n");
      out.write("const bno = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("\n");
      out.write("////localhost:8080/replies/49999/list?page=1&size=10\n");
      out.write("function getReplies(pageNum, goLast){\n");
      out.write("  \n");
      out.write("  axios.get(`/replies/${bno}/list`, {\n");
      out.write("    params: {\n");
      out.write("      page: pageNum || currentPage,\n");
      out.write("      size: currentSize\n");
      out.write("    }\n");
      out.write("  }).then(\n");
      out.write("    res => {      \n");
      out.write("      const data = res.data;\n");
      out.write("      console.log(data);\n");
      out.write("      const {totalCount, page, size}  = data;\n");
      out.write("\n");
      out.write("      if( goLast && (totalCount > (page*size)) ){\n");
      out.write("        const lastPage = Math.ceil(totalCount/size);\n");
      out.write("        getReplies(lastPage);\n");
      out.write("      }else{\n");
      out.write("        currentPage = page;\n");
      out.write("        currentSize = size;\n");
      out.write("        printReplies(data)\n");
      out.write("      }\n");
      out.write("\n");
      out.write("    }\n");
      out.write("  );  \n");
      out.write("}\n");
      out.write("\n");
      out.write("const replyList = document.querySelector(\".replyList\");\n");
      out.write("\n");
      out.write("function printReplies(data){\n");
      out.write("  const {replyDTOList, page,size, prev, next, start, end, pageNums}  = data;\n");
      out.write("\n");
      out.write("  let liStr = \"\";\n");
      out.write("\n");
      out.write("  for(replyDTO of replyDTOList){\n");
      out.write("    liStr +=  `<li class=\"list-group-item\" data-rno=\"${replyDTO.rno}\">\n");
      out.write("                  <div class=\"d-flex justify-content-between\">\n");
      out.write("                    <div>\n");
      out.write("                      <strong>${replyDTO.rno}</strong> - ${replyDTO.replyText}\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"text-muted small\">\n");
      out.write("                      ${replyDTO.replyDate}\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"mt-1 text-secondary small\">\n");
      out.write("                    ${replyDTO.replyer}\n");
      out.write("                  </div>\n");
      out.write("                </li>`\n");
      out.write("\n");
      out.write("  }//end for\n");
      out.write("\n");
      out.write("  replyList.innerHTML = liStr\n");
      out.write("\n");
      out.write("  let paginStr = \"\";\n");
      out.write("\n");
      out.write("  if(prev){\n");
      out.write("    paginStr += `<li class=\"page-item\">\n");
      out.write("                    <a class=\"page-link\" href=\"${start-1}\" tabindex=\"-1\">이전</a>\n");
      out.write("                  </li>`;\n");
      out.write("  };\n");
      out.write("\n");
      out.write("  for(let i of pageNums){\n");
      out.write("    paginStr += `<li class=\"page-item ${i===page ? 'active' : ''}\">\n");
      out.write("                    <a class=\"page-link\" href=\"${i}\">${i}</a>\n");
      out.write("                  </li>`;\n");
      out.write("  };\n");
      out.write("\n");
      out.write("  if(next){\n");
      out.write("    paginStr += `<li class=\"page-item\">\n");
      out.write("                    <a class=\"page-link\" href=\"${end + 1}\">다음</a>\n");
      out.write("                  </li>`\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  document.querySelector(\".pagination\").innerHTML = paginStr;\n");
      out.write("}\n");
      out.write("\n");
      out.write("document.querySelector(\".pagination\").addEventListener(\"click\", e => {\n");
      out.write("  e.preventDefault();\n");
      out.write("  e.stopPropagation();\n");
      out.write("\n");
      out.write("  const target = e.target;\n");
      out.write("\n");
      out.write("  const href = target.getAttribute(\"href\");\n");
      out.write("  if(!href){\n");
      out.write("    return ;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  console.log(href);\n");
      out.write("  getReplies(href);\n");
      out.write("\n");
      out.write("}, false);\n");
      out.write("\n");
      out.write("getReplies(1 , true);\n");
      out.write("\n");
      out.write("const replyModal = new bootstrap.Modal(document.querySelector(\"#replyModal\"));\n");
      out.write("const replyModForm = document.querySelector(\"#replyModForm\");\n");
      out.write("\n");
      out.write("replyList.addEventListener(\"click\", e => {\n");
      out.write("  \n");
      out.write("  //가장 까까운 상위 li 요소를 찾는다\n");
      out.write("  const targetLi = e.target.closest(\"li\");  \n");
      out.write("  \n");
      out.write("  /*\n");
      out.write("    data-xxx 형태의 속성은 HTML의 사용자 정의 데이타 속성\n");
      out.write("    브라우저가 의미를 해석하지 않고, js에서 꺼내 쓰라고 존재하는 값!\n");
      out.write("    예시> data-rno, data-replyer, data-reply등등...\n");
      out.write("  */\n");
      out.write("\n");
      out.write("  const rno = targetLi.getAttribute(\"data-rno\");\n");
      out.write("  \n");
      out.write("  console.log(rno);\n");
      out.write("\n");
      out.write("  if(!rno){ return }\n");
      out.write("\n");
      out.write("  axios.get(`/replies/${rno}`).then(res => {\n");
      out.write("    const targetReply = res.data;\n");
      out.write("\n");
      out.write("    console.log(targetReply);\n");
      out.write("\n");
      out.write("    if(targetReply.delflag == false){\n");
      out.write("      replyModForm.querySelector(\"input[name = 'rno']\").value = targetReply.rno;\n");
      out.write("      replyModForm.querySelector(\"input[name = 'replyText']\").value = targetReply.replyText\n");
      out.write("\n");
      out.write("      replyModal.show();\n");
      out.write("\n");
      out.write("    }else{\n");
      out.write("      alert(\"삭제된 댓글은 조회할 수 없습니다.\");\n");
      out.write("    }\n");
      out.write("  });\n");
      out.write("\n");
      out.write("}, false);\n");
      out.write("\n");
      out.write("//삭제\n");
      out.write("document.querySelector(\".btnReplyDel\").addEventListener(\"click\", e => {\n");
      out.write("  e.preventDefault();\n");
      out.write("  e.stopPropagation();\n");
      out.write("\n");
      out.write("  const formData = new FormData(replyModForm);\n");
      out.write("\n");
      out.write("  const rno = formData.get(\"rno\"); \n");
      out.write("\n");
      out.write("  axios.delete(`/replies/${rno}`).then( res => {\n");
      out.write("    const data = res.data;    //{\"result\": \"deleted\"}\n");
      out.write("\n");
      out.write("    alert(\"삭제 성공했습니다.\");\n");
      out.write("  \n");
      out.write("    replyModal.hide();\n");
      out.write("\n");
      out.write("    getReplies(currentPage);\n");
      out.write("  });\n");
      out.write("\n");
      out.write("}, false);\n");
      out.write("\n");
      out.write("\n");
      out.write("//수정\n");
      out.write("document.querySelector(\".btnReplyMod\").addEventListener(\"click\", e=>{\n");
      out.write("  e.preventDefault();\n");
      out.write("  e.stopPropagation();\n");
      out.write("\n");
      out.write("  const formData = new FormData(replyModForm);\n");
      out.write("\n");
      out.write("  const rno = formData.get(\"rno\");\n");
      out.write("\n");
      out.write("  axios.put(`/replies/${rno}`, formData ).then(res => {\n");
      out.write("    const data = res.data;\n");
      out.write("\n");
      out.write("    alert(\"수정이 성공했습니다.\");\n");
      out.write("    replyModal.hide();\n");
      out.write("    getReplies(currentPage);\n");
      out.write("  })\n");
      out.write("  \n");
      out.write("}, false);\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("    ");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/board/read.jsp(19,57) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /WEB-INF/views/board/read.jsp(24,70) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent(null);
    // /WEB-INF/views/board/read.jsp(29,74) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent(null);
    // /WEB-INF/views/board/read.jsp(34,71) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f4.setParent(null);
    // /WEB-INF/views/board/read.jsp(39,72) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.createdDate}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
    if (_jspx_th_c_005fout_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/board/read.jsp(43,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setVar("readUrl");
    // /WEB-INF/views/board/read.jsp(43,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/board/list");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_eval_c_005furl_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_c_005furl_005f0 != jakarta.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005furl_005f0);
      }
      do {
        out.write("\n");
        out.write("			  ");
        if (_jspx_meth_c_005fparam_005f0(_jspx_th_c_005furl_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("			  ");
        if (_jspx_meth_c_005fparam_005f1(_jspx_th_c_005furl_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("			  ");
        if (_jspx_meth_c_005fparam_005f2(_jspx_th_c_005furl_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("			  ");
        if (_jspx_meth_c_005fparam_005f3(_jspx_th_c_005furl_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("			");
        int evalDoAfterBody = _jspx_th_c_005furl_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_c_005furl_005f0 != jakarta.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_c_005furl_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f0 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    _jspx_th_c_005fparam_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fparam_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
    // /WEB-INF/views/board/read.jsp(44,5) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f0.setName("page");
    // /WEB-INF/views/board/read.jsp(44,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fparam_005f0 = _jspx_th_c_005fparam_005f0.doStartTag();
    if (_jspx_th_c_005fparam_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f1 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    _jspx_th_c_005fparam_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fparam_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
    // /WEB-INF/views/board/read.jsp(45,5) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f1.setName("size");
    // /WEB-INF/views/board/read.jsp(45,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f1.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fparam_005f1 = _jspx_th_c_005fparam_005f1.doStartTag();
    if (_jspx_th_c_005fparam_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f2 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    _jspx_th_c_005fparam_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fparam_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
    // /WEB-INF/views/board/read.jsp(46,5) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f2.setName("types");
    // /WEB-INF/views/board/read.jsp(46,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f2.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${types}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fparam_005f2 = _jspx_th_c_005fparam_005f2.doStartTag();
    if (_jspx_th_c_005fparam_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f3 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    _jspx_th_c_005fparam_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fparam_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
    // /WEB-INF/views/board/read.jsp(47,5) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f3.setName("keyword");
    // /WEB-INF/views/board/read.jsp(47,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f3.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fparam_005f3 = _jspx_th_c_005fparam_005f3.doStartTag();
    if (_jspx_th_c_005fparam_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f3);
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sec_005fauthentication_005f0.setParent(null);
    // /WEB-INF/views/board/read.jsp(53,11) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sec_005fauthentication_005f0.setProperty("principal");
    // /WEB-INF/views/board/read.jsp(53,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sec_005fauthentication_005f0.setVar("secInfo");
    int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
    if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    _jspx_th_sec_005fauthentication_005f1.setPageContext(_jspx_page_context);
    _jspx_th_sec_005fauthentication_005f1.setParent(null);
    // /WEB-INF/views/board/read.jsp(54,11) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sec_005fauthentication_005f1.setProperty("authorities");
    // /WEB-INF/views/board/read.jsp(54,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sec_005fauthentication_005f1.setVar("roles");
    int _jspx_eval_sec_005fauthentication_005f1 = _jspx_th_sec_005fauthentication_005f1.doStartTag();
    if (_jspx_th_sec_005fauthentication_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/board/read.jsp(56,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!board.delFlag && \n          	(secInfo.uid == board.writer || fn:contains(roles, 'ROLE_ADMIN'))}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("            <a href='/board/modify/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("'>\n");
        out.write("            	<button type=\"button\" class=\"btn btn-warning btnModify\" >MODIFY</button>\n");
        out.write("            </a>	\n");
        out.write("          ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
